### ISSUE TITLE
metrics-exporter-prometheus: compilation errors

### ISSUE THREAD

**Issue by kilpatty** [metrics-rs/metrics#113]
I'm seeing a lot of compilation errors on the latest alphas: 

```
error[E0050]: method `register_counter` has 3 parameters but the declaration in trait `metrics::Recorder::register_counter` has 4
   --> /Users/sean/.cargo/registry/src/github.com-1ecc6299db9ec823/metrics-util-0.4.0-alpha.4/src/debugging.rs:113:25
    |
113 |     fn register_counter(&self, key: Key, _description: Option<&'static str>) {
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 4 parameters, found 3
    |
    = note: `register_counter` from trait: `fn(&Self, metrics::Key, std::option::Option<metrics::Unit>, std::option::Option<&'static str>)`
```

I'm guessing this is related to how metrics and metrics util are linked in the Cargo.toml? (https://github.com/metrics-rs/metrics/blob/main/metrics-exporter-prometheus/Cargo.toml#L19-L20)

**Comment by tobz** [comment]
Ah, probably/maybe.  The alpha stuff gets tricky fast. 😅 

I _think_ a `cargo update` for `metrics-util` would get you a recent enough version.  `v0.40-alpha.5` and above should work correctly.

Can you try and let me know if it works?

**Comment by kilpatty** [comment]
No worries, I find this project extremely useful so thank you for that!

No luck on the cargo update. I think what's happening is that if you have the entire repository local, then the `metrics-exporter-prometheus` since the `path` config option for it's dependencies overrides the `version` config. 

Would you mind if I submitted a PR bumping `metrics-exporter-prometheus`'s deps to the latest versions published?

**Comment by tobz** [comment]
For both asks: 👍

**Comment by kilpatty** [comment]
Great! I've put up a PR for it here: #116. I can jump back into it later tonight to polish anything needed. 

Strangely I've not been able to reproduce my error with the versioning on the alphas... so waiting to push up a PR for that. Will look into that more tonight as well.

**Comment by kilpatty** [comment]
Haven't been able to replicate this, so I will close for now
