### ISSUE TITLE
Switch to binary naming scheme for data storage units.

### ISSUE THREAD

**Issue by tobz** [metrics-rs/metrics#118]
Per a discussion in Discord (https://discord.com/channels/500028886025895936/632238397259382827/775216386803761172), there's some confusion on whether or not the storage/data rate units were binary vs decimal exponentiation.  This is the difference between "megabyte" vs "mebibyte", or 1000 kilobytes vs 1024 kilobytes.

As Ralith points out, data rate-based units are almost always defined as decimal exponents, whereas storage tends to be binary.  We should likely change the unit variants here such that we end up with `Mebibytes` and `MegabytesPerSecond`.

In addition, we should update the documentation to call out the difference, and why it exists as it does, since many people will colloquially refer to 1024^2 bytes as a "megabyte," not "mebibyte".

**Comment by Ralith** [comment]
Data rates delimited in bytes and quantities delimited in bits are a bit weird. Is there a canonical convention defined for those? My intuition is that anything measuring in bytes should be binary, and anything using bits should be decimal.

**Comment by tobz** [comment]
The original design for units is based off of Cloudwatch's supported units since it seemed to be the most expansive compared to other existing metrics collection backends/services, but as you say it here out loud, I would agree.
