### ISSUE TITLE
Reset/Overwrite counter

### ISSUE THREAD

**Issue by jose-pr** [metrics-rs/metrics#119]
Is it possible to reset the value or set the value of a counter? Maybe by gauge and counter using the same backend so it would be possible to do:
counter!("val1", 1); val1 = 1
counter!("val1", 2); val1 = 3
gauge!("val1", 0); val1 = 0
counter("val1", 4); val1 = 4
gauge("val1", 10); val1 = 10
counter("val1", 5); val1 = 15

**Comment by tobz** [comment]
Theoretically, an exporter could make it possible to do something like this if you really wanted it.  We won't do it in `metrics` or any of the official exporter implementations, though.  It breaks some fundamental expectations how how the data is treated.

Sorry. :(

**Comment by jose-pr** [comment]
Then would it be possible for any of the followings:
-  to add a new options for gauge! so that we can add to it previous value: gauge!("val1", +1) or gauge!("val1",-1), and adding a new method to the Recorder trait to account for inc/dec a gauge. It looks like the method exist already on metrics-runtime for gauge.
- According to metrics-runtime docs: Counters represent a single value that can only ever be incremented over time, or reset to zero.  What is the way to reset it to Zero?

**Comment by tobz** [comment]
> * add a new options for gauge! so that we can add to it previous value: gauge!("val1", +1) or gauge!("val1",-1), and adding a new method to the Recorder trait to account for inc/dec a gauge. It looks like the method exist already on metrics-runtime for gauge.

Generally speaking, this seems like a much more likely thing for us to do.  I've opened #120 to explore the idea.

> * According to metrics-runtime docs: Counters represent a single value that can only ever be incremented over time, or reset to zero.  What is the way to reset it to Zero?

Practically, they should not reset to zero unless your application has restarted.  Again, this is something a customized exporter could potentially allow you to achieve.
