### ISSUE TITLE
Consider increment/decrement capabilities for gauges.

### ISSUE THREAD

**Issue by tobz** [metrics-rs/metrics#120]
Per #119, it seems like there's potentially some room for making gauges somewhat easier to work with.  In contrast with counters and histograms, gauges are the only metric type where a caller must themselves store the gauge value and find a way to periodically update it.  This could be obviated by having a way to allow encoding increment/decrement options so that callers could avoid tracking this state themselves, instead deferring to the installed recorder.

Thoughts/potential snafus:
- could this be a new type/enum that encodes absolute value vs incremental value?
- should it be brand new macros or some funky syntax for the existing one to emulate the above?
- do any of the common metrics collection systems allow deltas for gauges? is there a benefit beyond ergonomics to providing this as such?

**Comment by jose-pr** [comment]
> * should it be brand new macros or some funky syntax for the existing one to emulate the above?

I would propose a minimal change in gauge!, which should not be a breaking change. recognizing a + before the value to indicate it is a delta/increment example:
` gauge!("value.key", +val);`

And tying that to a new method on the recorder trait:
``
fn increment_gauge(&self, key: Key, value: f64);
``

Should be minimal changes and could integrate with the methods already provided by metrics-runtime to increment a gauge.

My main use would be to create a meter for throughput with the use of 2 gauges, adding byte count to a gauge and setting duration in another, and could utilize a proxy to calculate the rate as a another gauge, with the option to reset the meter. 
It would also enable counter like function with setting their values or resetting them.

**Comment by tobz** [comment]
We've added support for incrementing/decrementing gauges in #138 via two new macros: `increment_gauge!` and `decrement_gauge!`, with a very small tweak to `Recorder::update_gauge` to handle the absolute value vs incremental value usage.
