### ISSUE TITLE
Should ingestion/recording be chainable or seperate?

### ISSUE THREAD

**Issue by tobz** [metrics-rs/metrics#15]
High level: we likely want to define a trait in `metrics-core` for the input side of things.

We have `Recorder` which allows composability of the output side, but we don't yet have a trait to allow composability from the input side.  This trait is arguably the most useful because it means plugging in `metrics` to a system, or any `metrics` competitor, would Just Work (tm) if they implemented the trait.

Now, the question is: do we add a new trait or do we make the ingest side support `Recorder`?

Right now, our proscribed way to use `metrics` is to create a `Receiver`, which holds everything, and then to use a recorder/exporter to deliver those metrics to the console, or to Prometheus, or whatever external system there is.  `Sink`, in this scenario, would implement some trait that generalizes the recording of counters/gauges/histograms.

Technically, `Recorder` already has matching signatures to do just that.  If both `Sink` and exporters shared the `Recorder` trait, they could be literally chained together.  In some cases, users may not even want/need `Receiver`/`Sink`, and they would just wire up an exporter and be, essentially, collecting/exporting a metric within the same method call.

Now, of course, then they'd have no aggregation of values, and other impractical things, and then there's the question of whether or not it would really make sense to require callers to record histogram values by always having to pass a slice: nobody is logging timing calls with a slice, that's just our concession to make it easier to feed all the recorder values to the exporter without the function call overhead of calling `record_histogram` for every single datapoint.

All of that said, I think we may want to consider it.  A new trait gets us a cleaner looking API contract, but closes the door on potentially interesting uses of chaining these components together arbitrarily.

**Comment by LucioFranco** [comment]
I do think we want to separate Ingestion from recording since they are on the opposite side of the process. Imo this is an important distinction.

**Comment by tobz** [comment]
This issue is no longer relevant: the facade macros detach ingestion from recording.
