### ISSUE TITLE
The macros no longer support dynamic keys

### ISSUE THREAD

**Issue by Marwes** [metrics-rs/metrics#165]
Why was this removed in 0.13? It is still possible to call the recorder methods manually but constructing the Key is rather annoying. Used dynamic keys for things like:
```rust
metrics::counter!(format!("response_status_{}", response.status().as_u16()), 1);
```

**Comment by tobz** [comment]
Well, the simple answer is: practically speaking, we never designed it to be specifically allowed, and it working as such was mostly a side effect of all of the `Into` impls we had.  The example you gave would normally be achieved with something like:

```rust
metrics::increment!("http_responses", "status" => response.status().as_u16().as_str());
```

There's probably a way to bring this back: `Key`/`KeyData` definitely support initialization from owned strings.  The only current hurdle is the macros themselves, and the arguments they expect.  I'll have to think about it.

**Comment by tobz** [comment]
I've been toying with the macro stuff, and this is totally doable.  I'm still in the process of going through and adding a lot more unit tests to make sure this works as intended in all cases.

You can follow the PR: #170

**Comment by tobz** [comment]
Merged and released.  I cut all new minors for essentially all of the crates.  Given the new tests that were added, there's fairly solid coverage of the macros, but let me know if anything seems amiss.
