### ISSUE TITLE
Seems like unsafe code violates guarantees

### ISSUE THREAD

**Issue by Justarone** [metrics-rs/metrics#171]
I am not very experienced developer on Rust so don't be shy to correct me if I am wrong

What do I mean:
I've been using your create to implement my own graphite-metrics-exporter and in my case I've had to use interior mutability pattern (there is an async Sender inside of recorder). I've implemented this pattern with RefCell and the main problem is that RefCell have been used in multiple threads sometimes, which then become a cause of panic or other problems (remember that RefCell is not Sync). Compiler didn't notice anything for me (of course I would use Mutex if it did). 

So, I understand that very safety solutions, which prevent this behavior, may hit performance much, so I want you at least notice this fact in your documentation (that user should pay attention that guarantees may be violated and compiler won't issue that)

**Comment by tobz** [comment]
In general, I'm confused on why you would _need_ a `RefCell`.  Most exporter patterns will use a synchronous channel that only requires `&self`, or if you really need an asynchronous channel, you would use something like Tokio's `mpsc` channel, whose `Sender` has `blocking_send` which only requires `&self`.

This sounds like it probably comes down not being familiar with the options at hand, so I hesitate to change the documentation in a way that might have people worrying about something they don't need to really worry that much about.

Feel free to come chat with us on Discord -- https://discord.gg/9VngTFZ3hR, #metrics -- if you want some hands-on help with your exporter implementation.  We can probably give you some pointers to avoid needing `RefCell`. 👍🏻 

I'm going to close this ticket for now as it doesn't seem like there's anything specific for us to fix/document.

**Comment by Justarone** [comment]
Yeah, thank you for fast answer!
I've started implement this exporter, when tokio was 0.3, so there wasn't blocking_send method. You gave very good hint, I'll implement it this way, thanks!
