### ISSUE TITLE
Updating counter! with absolute value instead of delta

### ISSUE THREAD

**Issue by pablosichert** [metrics-rs/metrics#172]
Hey there, thanks for this handy crate!

I'm currently trying to update a counter with an absolute value, because I retrieve it from an external source and would like to avoid calculating the delta locally before emitting the metric. Currently, this does not seem possible, unless I am missing something.

I was wondering what the design decision was behind `increment_counter!(···)` being an alias for `counter!(···, 1)`?

Alternatively, the `counter!` could use `metrics::CounterValue::Absolute` and `increment_counter!` `metrics::CounterValue::Increment`, similarly how `gauge!`s are handled.

If this breaking change is not desired, an `update_counter!` macro could be introduced.

Would like to here your thoughts on this, and would be looking forward to submit a PR.

**Comment by tobz** [comment]
From simple to complex explanation...

> I was wondering what the design decision was behind increment_counter!(···) being an alias for counter!(···, 1)?

Simplicity.

> I'm currently trying to update a counter with an absolute value, because I retrieve it from an external source and would like to avoid calculating the delta locally before emitting the metric. Currently, this does not seem possible, unless I am missing something.

Counters are monotonic.  If we allow absolute value updates, we can not provide that invariant.  If you need a value that is updated via absolute values, you can use a gauge.  Unfortunately, this isn't something we're willing to change as it's integral to the library and the design.

I realize that this is a problem for some folks who really want external counters and don't want gauges, but `metrics` is designed for users emitting metrics, not for systems that are forwarding/aggregating them.  The goals are different.

**Comment by binarylogic** [comment]
Thanks @tobz

> I realize that this is a problem for some folks who really want external counters and don't want gauges, but metrics is designed for users emitting metrics, not for systems that are forwarding/aggregating them. The goals are different.

For this particular use case, I think the goals are aligned. We're attempting to instrument library usage, `rdkafka` to be exact, which provides its own internal metrics API. This isn't specific to Vector, and I could see any project wanting to instrument library usage, such as `rdkafka`, bumping into this problem.

> If this breaking change is not desired, an `update_counter!` macro could be introduced.

Is there any reason something like this would not be accepted given the above? That seems like a reasonable non-breaking change.

@pablosichert correct me if I'm wrong on any of this.

**Comment by pablosichert** [comment]
Just one thing to add:

> If we allow absolute value updates, we can not provide that invariant.

If this is a concern, couldn't the invariant be checked in the recorder implementation?

**Comment by tobz** [comment]
Right, I understand the premise, but enforcing it the way it is done now is what provides the invariant, so that all exporters don't have to do it themselves.

Adding a new macro would avoid a breaking change to the existing macros, but still requires dropping our counter monotonicity invariant.  Now _every_ exporter has to handle the case of a counter going backwards.  Just to drive the point home here: take a look at the StatsD protocol, or the Rust Prometheus library, or Java's Micrometer: none of them let you push an absolute value for counters.  Everything is delta-based.  This is the interface that consumers expect, for better or worse.

My preferred approach, which is something we did in metrics 0.12, but has no current analogue in 0.13, would be to have a proxy/pass-through for these metrics, that almost like... slurps them up at the time of pushing downstream.  Think registering a closure that is invoked every time a Prometheus scrape endpoint is hit.  This would still have to live somewhere in the exporter, but it's a cleaner separation from the core logic/invariants, and since it's per-exporter, then no exporter has to deal with it unless they have a way to support it.

**Comment by tobz** [comment]
Heck, actually, this could probably be done with a layer, now that I think of it.

The layer would match metrics by their name.  If a matching metric comes through, it can treat it as an absolute value and store that value in the layer.  The layer would calculate the delta between the current value and last known value of the metric, and emit the delta instead, finally updating itself to mark the value as the latest seen value, as well as handling monotonicity.

**Comment by tobz** [comment]
I'm going to reopen this for now because I think the layer approach is a workable solution.

**Comment by pablosichert** [comment]
Sounds good! Thanks for having had a second look at this issue.

I must admit that I hadn't searched the issues too well, and think that this one can be closed as a duplicate in favor of #66 or #81.

**Comment by tobz** [comment]
Just cut a new release of `metrics-util` with the `AbsoluteLayer` layer: `metrics-util@v0.6.1`.

As always, it has tests, and should work as advertised, but give it a whirl and let me know.

**Comment by binarylogic** [comment]
Thanks @tobz, that's very helpful!

**Comment by tobz** [comment]
As shown by timberio/vector#5874, there's likely a workable way -- performance-wise -- to provide the previously described `update_counter!` macro which handles writing an absolute counter value over time in a way where the delta is consistently updated, avoiding needing a layer to do so.

Reopening this issue as we should adding such a macro to `metrics` directly, as others have asked for this in the past so the appetite is clearly there.

**Comment by tobz** [comment]
This should be addressed by #240 at this point, as `Counter` exposes a method to directly set the absolute value for the given counter.

That said, there is no release of `metrics` yet that includes #240.

**Comment by tobz** [comment]
This is now released as part of `metrics@v0.18.0`.
