### ISSUE TITLE
Performance regression in `v0.13.0-alpha.13` -> `metrics-v0.14.1`

### ISSUE THREAD

**Issue by pablosichert** [metrics-rs/metrics#179]
Hey there!

We noticed in our [micro benchmarks](https://github.com/timberio/vector/blob/14176e939a92cbc0b6f09dfd6ccb912fc3d4fa54/benches/metrics_bench_util/mod.rs#L184-L297) that the upgrade from `0.13.0-alpha.13` to `0.14.1` introduced some noticeable performance regression: https://github.com/timberio/vector/pull/6442#issuecomment-779100160, https://github.com/timberio/vector/pull/6217#issuecomment-766435360.

~Skimming over https://github.com/metrics-rs/metrics/compare/metrics-v0.13.0...metrics-v0.13.1 I see~

~> - Gauges are now `f64` instead of `i64`.~
~> - Histograms are now `f64` instead of `u64`.~

~but I can't spot the change reflecting this in one code. The cost of floating-point vs integer arithmetic could partly explain the bump.~

Correct commit range: https://github.com/metrics-rs/metrics/compare/metrics-v0.13.0-alpha.13...metrics-v0.14.1.

Do you have some more insight to this?

**Comment by tobz** [comment]
Any chance you can highlight some of the specific data for the benchmarks alluded to here?

The changes mentioned were actually me backfilling the CHANGELOG itself, so really, nothing changed between `0.13.0` and `0.13.1` except for adding a `From<T>` implementation for our internal `Cow<'a, T>` type.

**Comment by pablosichert** [comment]
Hey @tobz, sorry for the delay. Below the data and corresponsing benchmark setup.

Taken from https://github.com/timberio/vector/pull/6217#issuecomment-766435360:

```
name                                                                  time       time change  throughput throughput change  p     change
metrics_snapshot/cardinality/1                                        576.44 ns  +7.1600%     unknown    unknown            0.00  regressed
metrics_snapshot/cardinality/10                                       4.0395 us  +11.885%     unknown    unknown            0.00  regressed
metrics_snapshot/cardinality/100                                      46.491 us  +15.303%     unknown    unknown            0.00  regressed
metrics_snapshot/cardinality/1000                                     516.62 us  +8.9227%     unknown    unknown            0.00  regressed
metrics_snapshot/cardinality/10000                                    5.9199 ms  +6.4559%     unknown    unknown            0.00  regressed
metrics_no_tracing_integration/micro/bare_counter                     114.60 ns  +38.066%     unknown    unknown            0.00  regressed
metrics_no_tracing_integration/micro/bare_counter_with_static_labels  154.95 ns  +46.875%     unknown    unknown            0.00  regressed
metrics_no_tracing_integration/micro/bare_counter_with_dynamic_labels 226.27 ns  +30.988%     unknown    unknown            0.00  regressed
metrics_no_tracing_integration/micro/ununsed_span                     117.14 ns  +37.755%     unknown    unknown            0.00  regressed
metrics_no_tracing_integration/micro/span_no_labels                   336.00 ns  +8.5848%     unknown    unknown            0.00  regressed
metrics_no_tracing_integration/micro/span_with_1_static_label         335.83 ns  +8.5668%     unknown    unknown            0.00  regressed
metrics_no_tracing_integration/micro/span_with_2_static_labels        342.69 ns  +10.114%     unknown    unknown            0.00  regressed
metrics_no_tracing_integration/micro/span_with_1_dynamic_label        336.16 ns  +8.1355%     unknown    unknown            0.00  regressed
metrics_no_tracing_integration/micro/span_with_2_dynamic_labels       337.05 ns  +8.5066%     unknown    unknown            0.00  regressed
metrics_off/micro/bare_counter                                        4.4220 ns  +15.388%     unknown    unknown            0.00  regressed
metrics_off/micro/bare_counter_with_static_labels                     4.4221 ns  +15.388%     unknown    unknown            0.00  regressed
metrics_off/micro/ununsed_span                                        4.7510 ns  +23.047%     unknown    unknown            0.00  regressed
metrics_on/micro/bare_counter                                         185.87 ns  +22.717%     unknown    unknown            0.00  regressed
metrics_on/micro/bare_counter_with_static_labels                      257.89 ns  +29.303%     unknown    unknown            0.00  regressed
metrics_on/micro/bare_counter_with_dynamic_labels                     295.98 ns  +23.696%     unknown    unknown            0.00  regressed
metrics_on/micro/ununsed_span                                         186.27 ns  +21.269%     unknown    unknown            0.00  regressed
metrics_on/micro/span_no_labels                                       656.60 ns  +6.4539%     unknown    unknown            0.00  regressed
metrics_on/micro/span_with_1_static_label                             672.02 ns  +6.5157%     unknown    unknown            0.00  regressed
metrics_on/micro/span_with_2_static_labels                            665.85 ns  +6.2272%     unknown    unknown            0.00  regressed
metrics_on/micro/span_with_1_dynamic_label                            675.26 ns  +6.9931%     unknown    unknown            0.00  regressed
```

and isolated in https://github.com/timberio/vector/pull/6442#issuecomment-779100160 to the bare [dependency upgrade](https://github.com/timberio/vector/pull/6442/files):

```
2021-02-14T05:08:37.5070766Z metrics_snapshot/cardinality/1                                                                       519.45 ns  +8.3179%     unknown         unknown            0.00  regressed
2021-02-14T05:08:37.5071474Z metrics_snapshot/cardinality/10                                                                      3.4979 us  +13.927%     unknown         unknown            0.00  regressed
2021-02-14T05:08:37.5072182Z metrics_snapshot/cardinality/100                                                                     40.773 us  +20.232%     unknown         unknown            0.00  regressed
2021-02-14T05:08:37.5072873Z metrics_snapshot/cardinality/1000                                                                    457.13 us  +13.004%     unknown         unknown            0.00  regressed
2021-02-14T05:08:37.5073642Z metrics_snapshot/cardinality/10000                                                                   5.1152 ms  +10.216%     unknown         unknown            0.00  regressed
2021-02-14T05:08:37.5111392Z metrics_off/micro/bare_counter                                                                       4.5637 ns  +15.296%     unknown         unknown            0.00  regressed
2021-02-14T05:08:37.5112101Z metrics_off/micro/bare_counter_with_static_labels                                                    4.4224 ns  +36.372%     unknown         unknown            0.00  regressed
2021-02-14T05:08:37.5113733Z metrics_off/micro/ununsed_span  
```

The corresponding part for testing the
- cardinality: https://github.com/timberio/vector/blob/master/benches/metrics_snapshot.rs#L29-L31
- bare counter: https://github.com/timberio/vector/blob/master/benches/metrics_bench_util/mod.rs#L190
- bare counter with static labels: https://github.com/timberio/vector/blob/master/benches/metrics_bench_util/mod.rs#L195
- unused span: https://github.com/timberio/vector/blob/master/benches/metrics_bench_util/mod.rs#L212

and others in the same file potentially supressed by the noise threshold.

**Comment by pablosichert** [comment]
I just noticed that I somehow picked a completely wrong version range. That should have been https://github.com/metrics-rs/metrics/compare/metrics-v0.13.0-alpha.13...metrics-v0.14.1 instead. Will take a look at the diff again.

**Comment by tobz** [comment]
Sorry for the delay here.

Looking at that updated diff, there were definitely more foundational changes that were made, namely the reworking of macros to support using owned strings for metric keys.  We had to significantly the macros, so I wouldn't be entirely surprised if the changes there are leading to suboptimal code somehow.

I'll see if I can check out the generated code for one of these test cases to understand where the differences may lie.

**Comment by tobz** [comment]
Spent some time poking at this, and just wanted to write down my thoughts...

- I too observed a small change in overhead of the basic macros, although more of the order of 4-6%, between the two tags.
- All the core data structures are the same size between the two tags, as far as I can see: `Key`, `KeyData`, `SharedString`, etc.
- The code generated by the procedural macros is also roughly the same: while some of the methods are different, they're simply using newer specialized versions i.e. switching from `KeyData::from_parts` to `KeyData::from_hybrid` which optimizes for cases where we have a static key vs dynamic labels, instead of forcing a clone of the key, etc etc.

There's still some rough ideas I have to take a look at things, but benchmarking at this granular of a level proves to be a bit painful when it comes to diagnosing minute differences.

**Comment by tobz** [comment]
Going to close this as it's very old and we've moved a few versions ahead at this point.
