### ISSUE TITLE
chore: cut new releases

### ISSUE THREAD

**Issue by tobz** [metrics-rs/metrics#201]
We've got a lot of changes in the chamber -- namely, key references -- plus some more sensitive fixes like #190.  We should get them out sooner rather than later.

**Comment by tobz** [comment]
Took care of this:
    `metrics@v0.15.1`
    `metrics-macros@v0.3.0`
    `metrics-util@v0.7.0`
    `metrics-exporter-prometheus@v0.4.0`
    `metrics-exporter-tcp@v0.3.0`
    `metrics-tracing-context@v0.4.0`

**Comment by koivunej** [comment]
@tobz I'm trying to upgrade from metrics-util 0.3.2 with #190 getting nagged on by `cargo-audit` on an ancient codebase. Is there an issue describing what happened to the different crates (metrics-runtime) after the last release (metrics-runtime 0.13.1, metrics 0.12.0), I wasn't able to find a changelog or similar.

**Comment by tobz** [comment]
Back then, I wasn't as regimented about changelogs, so unfortunately there's nothing I can point you to. The last release of `metrics-runtime` was `0.13.1`, though, before we switched to the newer `Recorder`-based API and `metrics` got the macros and all of that.
