### ISSUE TITLE
Figure out if if there's a way for metered and dipstick to work with metrics-core.

### ISSUE THREAD

**Issue by tobz** [metrics-rs/metrics#21]
Both @fralalonde and @magnet have expressed interest in making their libraries ([`dipstick`](https://github.com/fralalonde/dipstick) and [`metered`](https://github.com/magnet/metered-rs), respectively) compatible with `metrics`/`metrics-core`.

Just gonna dump some thoughts here:

## Ingestion
We need to come up with an ingestion trait, similar to [`Recorder`](https://docs.rs/metrics-core/0.3.1/metrics_core/trait.Recorder.html).  Until we have a trait, we can't reasonably expect these libraries, or others, to interoperate because then they'd just be tying themselves to `metrics` instead of `metrics-core`.

I think for `dipstick` this could be as easy as a new type of output scope that wraps a `TheoreticalMetricIngestTrait`, and I guess the inverse is also true: it could have an input scope that implements the trait.

For `metered`, I haven't looked closely enough at the code but given that it generates registry impls via procedural macros, I _think_ it's possible that it could have the auto-generated registries implement the trait and use it?  Not sure if it generates a field per specific metric or stores them generically: our plain interface only really works well if you can feed it a string for the metric name and the value, rather than treating it like a field that you map directly to a callsite.

## Exporting
Exporting only requires supporting [`SnapshotProvider`](https://docs.rs/metrics-core/0.3.1/metrics_core/trait.SnapshotProvider.html) and/or [`AsyncSnapshotProvider`](https://docs.rs/metrics-core/0.3.1/metrics_core/trait.AsyncSnapshotProvider.html).

Both libraries could have their own snapshot type -- just holds all the metric names -> values, really -- and implement the trait.  They'd also need to be able to provide a snapshot provider, like [`Controller`](), to actually take the snapshot.  That type would have to be thread-safe.

**Comment by magnet** [comment]
In `metered`, it should indeed be possible to implement the trait on generated registries. There is one generated registry for each annotated `impl` block, which contains sub-registries for each measured method, which contains one metric per field (for each metrics applied to the said method). This allows having no complex look-up logic associated to finding a metric, lets us keep the precise type for each metric (compared to erasing them or having enums in a generic storage), which in turns makes it easy to implement whatever traits we like.

**Comment by tobz** [comment]
I think that's maybe what makes it hard, though? The ingest interface is basically something like `update_counter(name: &str, value: u64)` so there's a little bit of erasure that you can't entirely avoid.

**Comment by magnet** [comment]
Tobz, you are right that makes it hard to implement using a generic wrapper, but I was thinking to implement the trait on generated registries (the trait implementation would be generated as well).

You would have something like `registry.record(&mut recorder)` that would call, for each metric `c`, `recorder.update_<metric_type>("<generated_metric_name>", c)`. We can also track whether metrics are counters, gauges or histograms.

Metered's API normally doesn't distinguish those, but nothing prevents us from implementing a trait returning a metric type.

These extra implementations could be behind feature gates.

As for generated registries, iirc there's an example in the documentation, otherwise `cargo expand` should help.

**Comment by tobz** [comment]
Similar to #16, this issue is sufficiently old that I think it would need a complete re-examination to understand where both crates could work together, and for the sake of clearing the backlog, I'm going to close this.
