### ISSUE TITLE
Feature/Documentation Request - Async Recorder

### ISSUE THREAD

**Issue by insanitybit** [metrics-rs/metrics#211]
Hey, I've been starting to look into this crate for my services and I was wondering how one would handle an async recorder. My use case is that I'd like to write metrics off to Kafka. I think an async Recorder would probably be generally useful for working in async contexts where you don't want to block your work on metrics recording and it'll make it easier to export via async clients like rdkafka.

Is this possible today? Or am I misunderstanding how to properly use metrics?

edit: I think the short version is "don't push metrics in a Recorder", which wasn't super clear to me but someone informed me that the right way is to spin up a separate thread to poll the Recorder and write the data off.

**Comment by tobz** [comment]
Yep, you're on the right path.

The `Recorder` interface is synchronous itself -- that will always be the case -- but you can easily push metrics into a channel and have a downstream thread/worker/whatever actually do the heavy lifting of processing and shipping those metrics somewhere else.

If your use case is shipping metrics in a condensed format without processing, you can take a look at `metrics-exporter-tcp`, which employs a comparable design to ship metrics off-thread to a background event loop that serves them over TCP.

Feel free to chat with us on Discord if you have more questions, but I'm going to close this issue for now. 👍🏻
