### ISSUE TITLE
support prometheus push gateway

### ISSUE THREAD

**Issue by NOBLES5E** [metrics-rs/metrics#215]
> Prometheus client libraries should have a feature to push the registered metrics to a Pushgateway.

https://github.com/prometheus/pushgateway

**Comment by NOBLES5E** [comment]
@tobz I'd like to help with the implementation if desired. But I'm not sure whether you think it should be implementation here.

**Comment by tobz** [comment]
@NOBLES5E I can't explicitly think of a reason why we _wouldn't_ want push gateway support in `metrics-exporter-prometheus`.  Feel free to start working on that, and you can reach out back here or in our [Discord](https://discord.gg/eTwKyY9) if you have questions or need help.

**Comment by NOBLES5E** [comment]
@tobz Thanks! Just created a draft PR here: https://github.com/metrics-rs/metrics/pull/217.
