### ISSUE TITLE
Initializing metrics before they're actually updated.

### ISSUE THREAD

**Issue by tobz** [metrics-rs/metrics#22]
Our internal architecture keeps metrics around forever -- so they never drop out, even if they have no update activity -- but we currently have no way to initialize them.

There's a few options here that I've been pondering:

- make the sink API register them if a user is getting a proxy object (this needs #13 to land)
- add a registration API either as a `Controller`/`Sink` thing or just literally add it to `Sink`

The upside to a registration API, I think, is the ability to provide a way to document metrics which could be used for exporters like Prometheus, etc.  We'd have to add to metrics-core to support that on the recorder side, but it'd be workable.

**Comment by LucioFranco** [comment]
I think it would be nice to support the ability to dynamically register them plus also statically.

**Comment by tobz** [comment]
Thinking this through a little bit more, and these are just sort of random thoughts:

- with #13 now in place, getting metric handles (`Counter`, `Gauge`, `Histogram`) will implicitly register a metric
- I've yet to see a popular metrics system that supports description data about metrics besides Prometheus, and most systems that interop with Prometheus just ignore it
- if you would be able to call something like `self.sink.register_counter(...)` then you can probably also store the `Counter` proxy handle directly

All of this is to say: I think landing proxy handles in #13 got us this feature in a minimal but viable form, so I'm going to close this for now.
