### ISSUE TITLE
No documentation for `push_gateway_config()` method on docs.rs

### ISSUE THREAD

**Issue by NOBLES5E** [metrics-rs/metrics#223]
https://docs.rs/metrics-exporter-prometheus/0.6.0/metrics_exporter_prometheus/struct.PrometheusBuilder.html

Could be `--all-featuers` not passed when generating documentation?

**Comment by tobz** [comment]
I believe we could do that?  What I'd like to do is follow [what `tracing` did](https://github.com/tokio-rs/tracing/issues/440) so that labels show up.  Otherwise, while we might show `push_gateway_config`, it wouldn't be clear that you actually need a feature flag to enable it.

**Comment by NOBLES5E** [comment]
yes what `tracing` did looks better

**Comment by tobz** [comment]
This is now released as part of `metrics-exporter-prometheus@v0.8.0`.

I also ended up overhauling a lot of the configuration flags, as cleaned up the code surrounding the different modes, so hopefully using the push gateway support should be a simpler and more lightweight experience now.
