### ISSUE TITLE
What happened to metrics-runtime?

### ISSUE THREAD

**Issue by simao** [metrics-rs/metrics#227]
This is not really an issue but I cannot use discord as it asks me for a mobile phone number to confirm my account.

What happened to the sources for https://docs.rs/metrics-runtime/0.13.1/metrics_runtime/ ? 

I'd like to use the log exporter but cannot find it in this repo. Trying to find the latest version so I can use it in my cargo.toml, but seems it has been abandoned?

Thanks

**Comment by tobz** [comment]
They still exist in this repository, under tags for the specific release.  For example, version 0.13.1 of `metrics-runtime` has a corresponding tag in the repository called `metrics-runtime-v0.13.1`.

At a higher level: yes, `metrics-runtime` is abandoned.  Users are encouraged to use or switch to `metrics` where possible, although `metrics-exporter-log` is also abandoned so there's no direct path to switch in your case.

**Comment by simao** [comment]
Any particular reason for it to be abandoned? Or just because not enough people use it? Or maintainers don't use it so they don't want to maintain it?

Thanks
