### ISSUE TITLE
Histogram metrics are not affected by idle_timeout in PrometheusRecorder

### ISSUE THREAD

**Issue by danielnelson** [metrics-rs/metrics#228]
When I create a PrometheusRecorder with an `idle_timeout`, the summary emitted using the `histogram!` macro never seem to be removed.

I expect this will be a problem for labels with dynamic values if the service does not restart periodically, since the number of metrics will build up.

Additionally, I'm using the summary for timing metrics, and the results have a tendency to become very flat over time and unresponsive to new changes in timing.  Is there a way I can adjust how much history is saved?

Here is an example program that shows the behavior.  I expected that all metrics would stop being reported after 10 seconds, I observe the counter being removed but not the summary.

```rust
use std::{convert::Infallible, net::SocketAddr};
use std::time::Duration;

use hyper::{Body, Request, Response, Server, StatusCode};
use metrics::{counter, histogram};
use metrics_exporter_prometheus::{PrometheusBuilder, PrometheusHandle};
use metrics_util::MetricKindMask;
use routerify::prelude::*;
use routerify::{Router, RouterService};

async fn metrics_handler(req: Request<Body>) -> Result<Response<Body>, Infallible> {
    let prom_handle = req.data::<PrometheusHandle>().unwrap();

    Ok(Response::builder()
       .status(StatusCode::OK)
       .body(Body::from(prom_handle.render()))
       .unwrap())
}

#[tokio::main]
async fn main() {
    let exporter = PrometheusBuilder::new()
        .idle_timeout(MetricKindMask::ALL, Some(Duration::from_secs(10)))
        .build();
    let prom_handle = exporter.handle();
    metrics::set_boxed_recorder(Box::new(exporter)).unwrap();

    let router = Router::builder()
        .data(prom_handle)
        .get("/metrics", metrics_handler)
        .build()
        .unwrap();

    let service = RouterService::new(router).unwrap();
    let addr = SocketAddr::from(([127, 0, 0, 1], 8000));
    let server = Server::bind(&addr).serve(service);

    counter!("request_total", 2);
    histogram!("request_duration_seconds", 1.0);

    println!("App is running on: {}", addr);
    if let Err(err) = server.await {
        eprintln!("Server error: {}", err);
    }
}
```

**Comment by tobz** [comment]
@danielnelson Again, sorry for the delayed response.

The above code does seem correct at face value.  What crate versions are you using?

**Comment by danielnelson** [comment]
Here are the metrics crates from the lockfile, let me know if you need more info:
```
[[package]]
name = "metrics"
version = "0.17.0"
--
[[package]]
name = "metrics-exporter-prometheus"
version = "0.6.0"
--
[[package]]
name = "metrics-macros"
version = "0.4.0"
--
[[package]]
name = "metrics-util"
version = "0.10.0"
```

**Comment by tobz** [comment]
So this is fixed in #261 -- thanks again for submitting this issue! -- but I haven't yet cut a release of `metrics-exporter-prometheus`, as I'm undertaking a big maintenance window to clear the backlog of bugs, pending PRs, pending refactors, etc.

I'm close to the end of the list of fixable/confirmed bugs, so hopefully I'll be able to cut new releases in a week or two. 👍🏻

**Comment by danielnelson** [comment]
I tried out the latest code on main, but I noticed a bug.  It seems that even metrics that are constantly being updated are removed after the idle_timeout.

For example, with this code both the histogram and counter will removed after 120s despite being updated every second.
```rust
async fn metrics_handler(req: Request<Body>) -> Result<Response<Body>, Infallible> {
    let exporter = req.data::<PrometheusHandle>().unwrap();

    Ok(Response::builder()
        .status(StatusCode::OK)
        .body(Body::from(exporter.render()))
        .unwrap())
}

async fn emit() {
    let mut rng = rand::thread_rng();
    loop {
        counter!("request_total", 2);
        histogram!("request_duration_seconds", rng.gen::<f64>());
        tokio::time::sleep(Duration::from_secs(1)).await;
    }
}

#[tokio::main]
async fn main() {
    let exporter = PrometheusBuilder::new()
        .idle_timeout(MetricKindMask::ALL, Some(Duration::from

If you prefer, I can open a new issue for this._secs(120)))
        .install_recorder().unwrap();

    let router = Router::builder()
        .data(exporter)
        .get("/metrics", metrics_handler)
        .build()
        .unwrap();

    let service = RouterService::new(router).unwrap();
    let addr = SocketAddr::from(([127, 0, 0, 1], 8000));
    let server = Server::bind(&addr).serve(service);

    println!("App is running on: {}", addr);
    tokio::join!(emit(), async { server.await.unwrap(); });
}
```

**Comment by tobz** [comment]
@danielnelson This should now be fixed as of #264.  Would be curious if you still see the issue.

**Comment by danielnelson** [comment]
Looks like its working, thanks

**Comment by tobz** [comment]
This is now released as part of `metrics-exporter-prometheus@v0.8.0`.

Thanks again for the original report and the testing/validation help as I worked on the fixes. 👍🏻
