### ISSUE TITLE
Support for 32-bit architectures?

### ISSUE THREAD

**Issue by jszwedko** [metrics-rs/metrics#235]
It looks like currently this crate doesn't build on `powerpc-unknown-linux-gnu`:

```
➜  metrics git:(main) cargo build --target=powerpc-unknown-linux-gnu
   Compiling serde v1.0.130
   Compiling prost v0.7.0
   Compiling tracing v0.1.29
   Compiling thiserror v1.0.30
   Compiling metrics v0.17.0 (/home/jesse/workspace/metrics/metrics)
error[E0432]: unresolved import `std::sync::atomic::AtomicU64`
 --> metrics/src/key.rs:7:32
  |
7 |     sync::atomic::{AtomicBool, AtomicU64, Ordering},
  |                                ^^^^^^^^^
  |                                |
  |                                no `AtomicU64` in `sync::atomic`
  |                                help: a similar name exists in the module: `AtomicU8`

error: aborting due to previous error
```

We discovered this by way of a user [trying to compile vector](https://github.com/vectordotdev/vector/discussions/9560) for `powerpc-unknown-linux-gnu`.

Is this a platform this crate would be interested in supporting? I imagine this would mean generally supporting 32-bit architectures.

**Comment by tobz** [comment]
No issue with trying to support them, nope!

Likely just need to do something like [this](https://github.com/metrics-rs/quanta/pull/52/files) across the entire crate.
