### ISSUE TITLE
Consider renaming metrics-core + metrics-facade

### ISSUE THREAD

**Issue by kazimuth** [metrics-rs/metrics#24]
This is just a suggestion - no problem if there isn't interest! I understand names can be a very touchy issue for bikeshedding :)

In my opinion the goal of `metrics` should be to achieve similar ecosystem penetration to `log` -- it should be a no-brainer for all rust crates to add metrics, since those metrics will add very little compile-time and run-time cost. I'd love to be able to turn on a prometheus exporter and already have most of my metrics predefined, or add a flag to my CLI app and instantly get a dump of execution telemetry. For that to happen, the metrics crate should provide a dead-simple API and an excellent documentation experience. And the most important part of documentation is names.

Currently, however, the names of the involved crates are a little confusing. The `metrics` crate is complex and opinionated, whereas basic functionality required for ecosystem interop is relegated to the crates `metrics-core` and `metrics-facade`. If the crates were released as-is, it'd be like if `fern` was named `log` and `log` was named `log-core`. Not the end of the world, but a little confusing, especially for what's aiming to become a fundamental piece of infrastructure.

So I'd like to suggest combining `metrics-core` + `metrics-facade` and renaming them to `metrics`, and renaming the current `metrics` crate to something like `metrics-runtime`, or even back to `hotmic`. This would also avoid privileging `metrics` over e.g. `metered` and `dipstick` -- since they'd all comply with the same basic interop stuff, they'd be on a level playing field.

I do think `metrics-facade` needs more work before it's ready for prime-time; I've got a PR partway done that offers some decent perf improvements, and I think it should be fairly straightforward to get `no_std` support fully functional as well.

Thoughts?

**Comment by LucioFranco** [comment]
As a small counter point, tokio operates similar to how metrics is currently setup. The `tokio` crate is batteries included which I think was kinda the goal with metrics, its just a crate the reexports the smaller individual crates. Really the important stuff is the glue that lives in `metrics-core` but those could be moved to their own crates that are small.

**Comment by tobz** [comment]
Yeah,

I can see where you're coming from, but I'm also of two minds here.

The `metrics` crate is high visibility, which is precisely what we wanted when we asked to take it over from the previous maintainer.  Further, it's always been a crate with an actual implementation.

That being said, from a "nice to have" perspective, it would be nice to `metrics` match `log` and be the facade crate.

This would all, indeed, make a lot more sense if `metrics` was in fact named something else, then we'd just just have `metrics` and `metrics-core` and then something along the lines of `metrics-runtime-native` or what have you.

I'll have to think on this a little bit.

**Comment by tobz** [comment]
This became reality in #27 

`metrics` is now the facade crate, providing the macros, global recorder, etc.  `metrics-runtime` is the actual bundled implementation that is `metrics` and `metrics-core`-compatible.
