### ISSUE TITLE
Allow use of const for description in register macros

### ISSUE THREAD

**Issue by thedodd** [metrics-rs/metrics#244]
It appears as though the macros currently do not allow this behavior. It appears as though they expect a static str.

Again, thanks for all of the great work on this project.

**Comment by tobz** [comment]
That is correct.

It should definitely be possible to allow this.  Same response as #243, essentially, though: willing to accept a PR, as I don't currently have time to work on this.

**Comment by tobz** [comment]
This should be fixed as of #260, but no release has been cut yet that includes it.

**Comment by tobz** [comment]
This is now released as part of `metrics@v0.18.0`.  Although I apparently forgot to update the macro docs for `register_*` to show using a constant, it should definitely be possible. 😂
