### ISSUE TITLE
Prometheus exporter lacks a Tokio-less implementation

### ISSUE THREAD

**Issue by Stumblinbear** [metrics-rs/metrics#246]
The TCP exporter currently **can** be used without Tokio, however the Prometheus exporter cannot. The builder for it has the internal data for a `listen_address` even if the Tokio feature is disabled. Its implies the existence of an std thread implementation, but there doesn't appear to be one.

Is there any particular reason this isn't included?

**Comment by tobz** [comment]
The simple answer is that I didn't need a blocking implementation of the
Prometheus exporter, and no one has ever submitted a PR for it.  Thus, no
blocking implementation. :)
