### ISSUE TITLE
Prometheus exporter renders label keys with periods in them unsanitized

### ISSUE THREAD

**Issue by mcronce** [metrics-rs/metrics#248]
I can throw together a minimal reproduction if needed, but tl;dr labels added via both macro and `Builder::add_global_label()` are being rendered exactly how I put them in.  I did find #29, but the fix (#95) _looks like_ it only covered metric names.

In case it's relevant, I am calling `Handle::render()` directly to send to the push gateway once at the end of a batch job; these jobs tend to be short lived and I'm not able to reliably predict how long they'll take, so setting a send interval isn't an option.

**Comment by tobz** [comment]
Yeah, no reproduction required.  Sanitization is definitely not consistent across all the relevant fields.
