### ISSUE TITLE
Lazy metrics evaluation

### ISSUE THREAD

**Issue by jean-airoldie** [metrics-rs/metrics#25]
I'm currently using `rust-prometheus` in my applications for monitoring, but I'm interested in this crate since it decouples the actual metrics for the exporter. Also the performance overhead seems much lower. However I have a few questions regarding a specific use case I have.

I'm using prometheus to export process specific metrics such as cpu usage, disk usage, and network usage, provided by the OS. However, since actually getting of these metrics is relatively expensive, for instance parsing the content of the `/proc/<pid>/` directory, it must be done infrequently. Is it possible to have such lazy evaluated metrics that would only be evaluated when required? Or would I need to manually evaluate these metrics at a given time interval and push them?

**Comment by tobz** [comment]
It's technically possible, for sure.  I think we could do it without any performance issues.

Thinking about it out loud:

    enum Measurement {
        Counter(MetricName, u64),
        Gauge(MetricName, i64),
    }

    impl Sink {
        ...
        pub fn proxy<N, F>(&mut self, f: F)
        where
            N: Into<MetricName>,
            F: FnMut() -> Vec<Measurement>,
        {
            ...
        }
    }

This would register the closure to be run every time a snapshot was taken, and it would let it return multiple measurements all in one go.

Does that sound like it would work for you?

**Comment by jean-airoldie** [comment]
Yep, sounds good.

**Comment by tobz** [comment]
Cool; I was playing with a design today that I think could work, but I need to land #27 first before I can move forward with it.  I'll update this issue once there's some progress. 👍
