### ISSUE TITLE
timing! macro improvements

### ISSUE THREAD

**Issue by jean-airoldie** [metrics-rs/metrics#26]
What do you think of having the `timing!` macro support the following syntax:
```rust
let result = timing!("perf.expensive_work", {
    /* some expensive work */
});

// Which would expand to:
let result = {
    let start = Instant::now();
    let result = { /* some expensive work */ };
    let end = Instant::now();
    Recorder::record_histogram("perf.expensive_work", end - start);

    result
};
```
As well as:

```rust
let result = timing!("perf.expensive_call", expensive_call());

//  Which would expand to:
let result = {
    let start = Instant::now();
    let result = expensive_call();
    let end = Instant::now();
    Recorder::record_histogram("perf.expensive_call", end - start);

    result
};
```
And maybe if no key is specified, it could default to the location of the call in the src.
```rust
let result = timing!(expensive_call());

// Which would expand to:
let result = {
    let start = Instant::now();
    let result = expensive_call();
    let end = Instant::now();
    // Note that this is a static str.
    let key = concat!(file!(), ':', line!());
    Recorder::record_histogram("key", end - start);

    result
};
```

**Comment by tobz** [comment]
I want the facade macros to be as simple as possible to encourage maximum adoption, and to that goal, I'm punting on having them do anything other than forward to a recorder. 

I hope to eventually get [`metered`](https://github.com/magnet/metered-rs) to support `metrics` as a backend (or to use the facade macros) as it already handles this, and other, scenarios with specific macros.

**Comment by jean-airoldie** [comment]
Nice, that metered crate is precisely what I had in mind.
