### ISSUE TITLE
no `describe_histogram` in the root

### ISSUE THREAD

**Issue by cyberliem** [metrics-rs/metrics#265]
Hi there I try to follow this example, however, the describe_histogram doesn't seem to be in the root of the packages.
https://github.com/metrics-rs/metrics/blob/a5d55120f41cfee11fb30343f8b983b0fdea262b/metrics/examples/basic.rs#L12

**Comment by tobz** [comment]
@cyberliem Hey there, sorry you're having issues getting the example to work.

Are you using a Git dependency on `main` itself? The referenced macro hasn't yet been released.
