### ISSUE TITLE
Find a better design for `Registry` to support generic keys and memoized hashing.

### ISSUE THREAD

**Issue by tobz** [metrics-rs/metrics#272]
As mentioned in #271, the new `Registry` design we implemented to support memoized hashing of keys (among other things) switched from allowing a generic key `K` to specifically requiring `metrics::Key`.

For certain use cases, this is suboptimal because end users may specifically want to use a custom key type after translating from `metrics::Key` on the `Recorder` frontend to whatever they want to use on the backend.

We should be able to find a design that allows us to constrain `K`, as well as sufficiently describe it, to allow `Registry` to understand what hasher it needs to use when rehashing.  Practically speaking, `Hashable` gets us halfway there, we just need a little more information to let the key type also tell us what hasher to use if we need to rehash.

**Comment by loyd** [comment]
Thanks for addressing the problem.

> we just need a little more information to let the key type also tell us what hasher to use if we need to rehash

Do you have an example of why a hasher should be customized instead of just exporting the used one by `metrics`?

**Comment by loyd** [comment]
Also, I've found that the previous implementation is not composable enough with additional information:
```rust
struct SomeKey {
    key: Key,
    additional_info: X,
}

impl Hashable for ExtKey {
    fn hashable(&self) -> u64 {
        // want to get a hash of `key`
        // and add hash of additional information
        // to get a new hash value
    }
}
```

Maybe it's better to use a hasher with the commutative property, or force hasing `Key` firstly. For instance, by getting incomplete hasher from `Key`:
```rust
self.key.hash()
    .append(self.additional_info)
    .finish()
```

Previously, I solved this by [using double hashing](https://github.com/elfo-rs/elfo/blob/3199e7ec16bafb129c056c3edd94e2268d4aabfb/elfo-telemeter/src/storage.rs#L47-L55), that increase probability of collisions.

**Comment by loyd** [comment]
I've totally forgotten to thank you for the change, it seems to be much more flexible now!
