### ISSUE TITLE
Make `Primitives` public for users can pass their own implementation.

### ISSUE THREAD

**Issue by tobz** [metrics-rs/metrics#274]
As mentioned in #271, `Primitives` is a private trait that users cannot implement, which leaves them stuck dealing with the default `StandardPrimitives` implementation.

This was an oversight and it should not have been released as private.

**Comment by nrxus** [comment]
I've also wanted this lately with the addition that the functions of the `Primitives` trait should include the key name as that can sometimes change the details of the returned counter/gauge/histogram handler.
