### ISSUE TITLE
Bump MSRV to 1.56

### ISSUE THREAD

**Issue by rukai** [metrics-rs/metrics#287]
Although there isnt an MSRV specified in the readme or elsewhere the CI does specify runs on rust 1.55 so I assume there is an undocumented MSRV of 1.55?

Bumping to 1.56 will allow updating to hashbrown 0.12.0

The old version of hashbrown is causing duplicate hashbrown dependencies in my dependency tree.

**Comment by tobz** [comment]
Woops, kind of forgot about this one.

I recently bumped the MSRV in CI to 1.56.1, although I haven't yet codified it via `rust-version` in the various Cargo.toml files.
