### ISSUE TITLE
prometheus exporter sanitizes valid metric names

### ISSUE THREAD

**Issue by goller** [metrics-rs/metrics#289]
I have a metric `compaction_level2_duration_ns` that is sanitized into `compaction_level__duration_ns`.  I believe this metric is a valid [prometheus name.](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels).

Here is a test that shows that it fails:

```rust
    #[test]
    fn check_sanitize() {
        let name = "compaction_level2_duration_ns".to_owned();
        let actual = sanitize_metric_name(&name);
        assert_eq!(name, actual);
    }
```

The sanitize code is here:

https://github.com/metrics-rs/metrics/blob/5f720a0a8f53aaee4bfa9de1d9fc470f1ed6b3c3/metrics-exporter-prometheus/src/formatting.rs#L111-L115

I think it is because it replaces the first n occurrences matching the predicate, regardless of their position.

**Comment by tobz** [comment]
Yep, you're definitely right.

@gnuvince has graciously submitted a PR to fix this over in #290.
