### ISSUE TITLE
Ability to register on-demand metrics (or callback-driven metrics)

### ISSUE THREAD

**Issue by reivilibre** [metrics-rs/metrics#291]
The Python prometheus library has the ability to have custom collectors registered, which for all intents and purposes are basically 'callbacks' that return metrics.

One use case here is that you can compute metrics on-demand, which might suit metrics which are perhaps more expensive to compute. Or alternatively, it also means you can compute metrics which are difficult to track incrementally (e.g. process memory usage).

I was wondering if you had any insights as to how/if this might fit in to `metrics`.

Of course, a work around is to add a timer on a reasonable interval.

**Comment by tobz** [comment]
Yeah, the Prometheus exporter is already more complex than I'm really comfortable with: exporters are simply meant to be a conduit from the macros/`Recorder` trait to the underlying storage system.

For example, we have to support some level of histogram configurability to support aggregated histograms vs aggregated summaries, and the same thing with supporting the push gateway vs exposing a scrape endpoint .. but capturing metrics is expressly intended to happen through the macros and `Recorder` interface, not as an exporter afterthought.

Given the new support for registering metrics and holding direct handles to their storage, along with support for updating counters in an absolute mode, I believe all the support necessary already exists to handle this without the exporter -- any exporter -- needing to be changed.

**Comment by reivilibre** [comment]
I suppose the question I'm left wondering is: what's a portable (exporter-agnostic) way of triggering 'just before' collection?
Doing it on a timer means that the frequency will either be too low (and duplicate readings will be recorded), or the frequency will be too high (needless work being done), or the readings might be out of phase with the collections (e.g. if Prometheus collects every 60 sec, and my timer records readings every 60 sec, then you can imagine a case where the readings sit around for 59 seconds in a buffer before Prometheus collects them).

This was not intended to be a Prometheus-specific question; I was merely referring to it as 'prior art', I guess, or context from prior experience.

Maybe this is just a PEBKAC or documentation problem if you believe this is already doable; would be very grateful for a pointer or two if so!

**Comment by reivilibre** [comment]
Maybe it would help to illustrate with some (poor, ill-thought) example pseudocode:

```rust
pub fn main() {
    register_gauge!("process_memory_bytes", Unit::Bytes);
    metrics::...::register_pre_collection_hook(|| {
        let memory_bytes = some::helper::crate::get_memory_bytes();
        gauge!("process_memory_bytes", memory_bytes as f64);
    });
}
```

**Comment by tobz** [comment]
The primary impedance mismatch here is that there's no concept of a "collection" in `metrics`: all metrics emissions are immediately forwarded to the installed global recorder (typically an exporter by itself) that decides when and how to then push those metrics "out" to the downstream system.

The approach should be to emit the metrics -- whatever the metrics may be -- on an interval that provides the desired granularity of measurements. It might be more work than if you only emitted them when an exporter actually needs to ship the metrics somewhere else, but it's also more consistent and simpler.

**Comment by reivilibre** [comment]
OK, thanks!
