### ISSUE TITLE
Moving to a reusable Recorder

### ISSUE THREAD

**Issue by jean-airoldie** [metrics-rs/metrics#33]
Related to #11, #30.

Currently, each time a snapshot is exported there are multiple (arguably) unnecessary allocations.

Lets say we look at the http metrics exporter code. This a small snippet extracted from https://github.com/metrics-rs/metrics/blob/master/metrics-exporter-http/src/lib.rs#L70.
```rust
// This is the main logic for the async event loop for the http exporter.
service_fn(move |_| {
    let recorder3 = recorder2.clone();

    controller2
        .get_snapshot_async()
        .then(move |result| match result {
            Ok(snapshot) => {
                let mut r = recorder3.clone();
                snapshot.record(&mut r);
                let output = r.into();
                Ok(Response::new(Body::from(output)))
            }
            Err(e) => Err(e),
        })
})
```
The following is some kind of pseudo code representation meant to illustrate the allocations made by this logic.

```
Controller::get_snapshot_async() {
    MetricsRegistry::get_snapshot() {
        Vec::new(); // allocates to hold metrics.
        ValueHandle::snapshot() {
            for value in values {
                Counter -> (),
                Gauge -> (),
                Histogram -> AtomicWindowedHistogram::snapshot() {
                    Vec::new(); // allocates to hold values
                }
            }
        }
    }
}
Recorder::clone() {
    HashMap::new();
    Vec::new();
}
Recorder::into<String>() {
  String::new();
}
```

So each time we allocate a new `Snapshot` and `Recorder` which is quite expensive.
What I suggest is that we get rid of the `Snapshot` entity and move to a reusable `Recorder`.
The logic would become something like this:
```rust
service_fn(move |_| {
    // The recorder should keep track of its state internally, so that it can
    // only be written to once.
    recorder.reset();
    // Takes a snapshot of the metrics and write them in the recorder. This might
    // allocate memory if needed.
    match controller.snapshot(&mut recorder) {
        Ok(_) => {
            let output: String = recorder.export();
            Ok(Response::new(Body::from(output)))
        }
        Err(e) => Err(e),
    }
})
```
This way we could reuse the allocated memory from the `Recorder` and only allocate the output `String`.

Admittedly, I am not currently certain that this is actually possible with the futures 0.1 runtime, but I'll work on a PR.

**Comment by tobz** [comment]
I think it's definitely possible.

What I'd like to do is keep around the ability to take an independent snapshot, though, because it provides flexibility if users need to do something with the raw data.

Ideally, I'd like to see `Controller` itself implement `Snapshot` just like `metrics_runtime::data::Snapshot` does -- although we might want to rename the trait to something more generic, dunno -- so that exporters and "internal" code can use the optimized, fewer-allocations `Controller`-based approach, while leaving the existing approach for anybody who needs it.

**Comment by jean-airoldie** [comment]
But what would be the current advantage of the current approach?

We could simply add a trait to `Recorder` that adds the ability to iterate over its content. So a user that wants a raw snapshot would create a recorder and then iterate over its content.

**Comment by tobz** [comment]
Also, I'd like to do the snapshot work first before we play with/try and move to reusable recorders.  That one still needs testing/thought, and I think the "controller records directly to recorders" thing is good and achievable right now.

**Comment by tobz** [comment]
I don't think it's a valid use case to create a recorder that simply holds the data in raw form.  `Snapshot` already does that, and will do it with less overhead than the recorder interface, because it lets us keep histograms compressed up until the moment that they need to be recorded.

**Comment by tobz** [comment]
I think we can close this out now that #35 has landed.
