### ISSUE TITLE
Memory usage goes through the roof when using Prometheus histograms (summaries)

### ISSUE THREAD

**Issue by jakubzytka** [metrics-rs/metrics#339]
Hi! We're using 
```
metrics = "0.20.1"
metrics-exporter-prometheus = "0.11.0"
```
in our program, with an HTTP server exposing a Prometheus scrape point.
We noticed a gigantic memory usage related to histograms.
I still haven't figured all things out, but I'm letting you know in case you were able to help and weigh in on some matters.

So far two distinct issues have been identified:

## 1. unbounded memory growth in histograms when `PrometheusHandle::render` is not called.

IIUC some raw histogram data gets "compacted" in:
https://github.com/metrics-rs/metrics/blob/64d5c5ae63babafbf3875f723ed263efe9332647/metrics-exporter-prometheus/src/recorder.rs#L93
There is no interface to trigger that other than `render`, which is suboptimal, because:
- there is no clear indication that it *must* be done (admittedly, I might have missed that in the docs, so please bear with me; that said, it is surprising)
- `render` does a bunch of things that are not really needed to compact the raw data
- typically `render` will be called when metrics scraping happens. There is no way to ensure scrapping from an external component, so one has to periodically call `render()` oneself; 

What about calling (or even better - scheduling background compaction) when there are too many recorded histogram samples (globally)? WDYT?

## 2. the actual memory allocations happening during `record` don't seem reasonable
In our not-so-small program according to heaptrack 75% of all allocations happen during `Histogram::record`:

![histogram-allocs](https://user-images.githubusercontent.com/9912906/211543646-39139e0d-32fc-45c4-9356-5e5896ea4206.png)

Furthermore, these allocations seem to have >1kb size (!??)
![alloc-sizes](https://user-images.githubusercontent.com/9912906/211543862-6ba4600a-177b-4a14-b5f8-d3d0ce48d67a.png)

This sounds a bit excessive :)
It looks as if every `record` was causing a creation of a new `Block` in `AtomicBucket::push`

**Comment by jakubzytka** [comment]
re 2:
I think it may be just us using the histogram too frequently.

**Comment by tobz** [comment]
As far as the first problem: yes, this is an outstanding issue (noted originally in #245) that I'm willing to accept a PR for. The linked issue lays out some possible approaches I'd accept for solving the problem.

As far as the second problem: histogram collection is based on `AtomicBucket`, which is an unbounded queue modeled after crossbeam's unbounded MPMC queue, `SegQueue`. It indeeds allocates memory in large blocks, which are closer to 512B, but with the additional fields, etc... I'm guessing the allocator is rounding up to 1KB.

However, it does _not_ allocate a block every time a sample is recorded. Blocks are allocated roughly every N samples, where N is the pointer width (in bits) of the platform, so 64 for x86-64, etc. If the current block is full, all contending writers will speculatively allocate a new block and try to install it, which can lead to additional allocations beyond the expected "once every N pushes" overhead.

`AtomicBucket` is fast, and generally it would be hard to truly use it "too frequently": it supports insertion rates in the millions/second, even with contention. However, depending on your constraints -- such as avoiding ongoing allocations at runtime -- it could certainly be unsuitable for a particular workload.

As the second problem is simply the nature of `AtomicBucket`, and the first problem is being tracked in #245, I'm going to close this issue.

**Comment by jakubzytka** [comment]
Thanks a lot for your fast response! I'll follow up in #245 

I'd like to comment on the "too frequently" part:
Our program processes ~1GB/s, and when not scraping the histograms (we have 2 frequently accessed ones) they consume ~160MB of heap per minute. That is not much in comparison but is very visible in our case because we aggressively reuse buffers to fit in a pretty tight memory budget we have.
