### ISSUE TITLE
Exporter should handle the Recorder convertion logic.

### ISSUE THREAD

**Issue by jean-airoldie** [metrics-rs/metrics#34]
Currently a `Recorder` is converted to a String via `Into<String>` trait. I think a better approach would be to provide a trait method to iterate over the contents of the `Recorder` so that an `Exporter` can implement the conversion logic directly. So the `Into<String>` trait would not be required.

**Comment by tobz** [comment]
Recorders are intended to define the formatting, and exporters are intended to define the transport.

The biggest reason that I chose to go with conversion traits is that not every recorder will output a string, and not every exporter will want a string.  I'm not sure it's a wise idea to expose the internal state of a recorder by fiat via the `Recorder` trait.

For one, it exposes internal state, potentially intermediate state, where the `From<T>` implementations are meant to signal a finalized conversion into their output format.  Secondly, if we encode this ability into a trait, it means that recorders can only output themselves in one format. 

With `From`/`Into`, a recorder can render itself into multiple output formats.

As a final example: `TextRecorder` defines a particular format for the metrics it renders... how they're indented, how they're structured, etc.  The recorder itself, as it's recording, is doing this formatting work.  How would an exporter implement the formatting logic without essentially becoming the formatter itself?

**Comment by jean-airoldie** [comment]
Makes sense.
