### ISSUE TITLE
Allow for declaration of set of labels without default values

### ISSUE THREAD

**Issue by CinchBlue** [metrics-rs/metrics#356]
Currently using `metrics` and `metrics-prometheus` and `prometheus`.

Consider:

```rust
// Declare each metric with their default values
metrics::register_counter!("failures", "comp_id" => "", "error" => "");

metrics::counter!("failures", 1, "error"=>"true", "comp_id" => "nba");
metrics::counter!("failures", 2, "error"=>"false", "comp_id" => "nba");
metrics::counter!("failures", 3, "error"=>"whaoasdfa", "comp_id" => "a123");
metrics::counter!("failures", 3, "error"=>"asdfqwe", "comp_id" => "b123", "wowow" => "owowoww");
```
        
when the metrics report is generated, you get:

```prometheus
# HELP failures failures
# TYPE failures counter
failures{comp_id="",error=""} 0
failures{comp_id="a123",error="whaoasdfa"} 3
failures{comp_id="nba",error="false"} 2
failures{comp_id="nba",error="true"} 1
```

This is not so great because there's the extra "default" metric

```
failures{comp_id="",error=""} 0
```

is there a way to not have to have this? I know the set of labels but not the full set of values.

**Comment by tobz** [comment]
The calls to `counter!` (or any other macro for _emitting_ a metric) will register a metric if it doesn't yet exist, so the call to `register_counter!` is extraneous here.

**Comment by CinchBlue** [comment]
I am using `metrics-prometheus` which allows for freezing metrics after a certain point: https://docs.rs/metrics-prometheus/0.3.1/metrics_prometheus/struct.FreezableRecorder.html

This allows downstream consumers of libraries that use `metrics` to only listen to the metrics that they desire, and then disallow the reporting of other metrics that are not specified.

**Comment by tobz** [comment]
Admittedly, taking a quick look at `metrics_prometheus::FreezableRecorder`... it looks like you'd have to register the _precise_ metrics that you want (i.e. the labels would need to be populated).

Registering a metric, and having it immediately show up despite not yet having been emitted, is pretty fundamental. It's not something that we would change on the `metrics` side, at least.

**Comment by CinchBlue** [comment]
Ok, that sounds reasonable. Thanks.
