### ISSUE TITLE
Scoped recorders

### ISSUE THREAD

**Issue by david-perez** [metrics-rs/metrics#389]
I'm testing a `Recorder` implementation and getting cross-test contamination because the recorder is shared across all threads and registered globally. I've had a look at how the crate tests its recorders and noticed how it uses [`Debugging::per_thread`](https://github.com/metrics-rs/metrics/blob/0193688dac4ca646dbe44620040c20b9abf9bf5e/metrics-util/src/debugging.rs#L216) for thread-local metrics, and [`clear_recorder`](https://github.com/metrics-rs/metrics/blob/0193688dac4ca646dbe44620040c20b9abf9bf5e/metrics/src/recorder.rs#L194) to test the entire recorder implementation in the same test, setting the recorder each time after clearing it. However, I don't think these ingredients suffice to test the same recorder implementation across different tests running in parallel in the same process.

I was wondering whether it's possible to introduce recorders that live within a scope, much like how [`tracing::dispatcher`](https://docs.rs/tracing/latest/tracing/dispatcher/index.html#setting-the-default-subscriber) allows to set a scoped subscriber:

```rust
let recorder = MyRecorder::new();
let dispatcher = metrics::dispatch::Dispatcher::new(recorder);

// no default recorder

metrics::dispatcher::with_default(&dispatcher, || {
    // `recorder` will handle metrics emitted within this scope.
});

// no default recorder again
```

**Comment by tobz** [comment]
This has definitely come up before and is likely something I'll tackle in the future since, as you note, it makes actually testing any code that uses `metrics` much more complex/finnicky.
