### ISSUE TITLE
Learning material

### ISSUE THREAD

**Issue by LukeMathWalker** [metrics-rs/metrics#422]
With my employer, we developed a workshop to teach folks the ropes about telemetry for Rust applications.  
It's entirely self-paced: it's a collection of exercises with tests to validate your solutions.
It covers the `metrics` crate in quite some detail in the [`03_metrics` section](https://github.com/mainmatter/rust-telemetry-workshop/tree/main/exercises/03_metrics). 

All exercises are available [on GitHub](https://github.com/mainmatter/rust-telemetry-workshop/tree/main) and the material is CC BY-NC 4.0 DEED licensed.

Is this something you might be interested in linking to from the README or the documentation, in the same vein of the [External resources](https://github.com/mainmatter/rust-telemetry-workshop/tree/main) section in `tracing`'s repo?

**Comment by tobz** [comment]
Hey there, this is nice. :)

I'd definitely be in favor of linking to it in the README. One thing that might add a little bit of complexity, though, is that as soon as we cut the next release of `metrics`, where things switch to `counter!("foo").increment(1)`, and so on, the guide will _potentially_ be out-of-date? I haven't read through all of it, though, so maybe it doesn't as heavily depend on existing code examples?

**Comment by LukeMathWalker** [comment]
It'll be out of date for a bit, but we're going to update it to the latest version shortly after it comes out 👍🏻

**Comment by tobz** [comment]
Just a heads up that I'll be cutting new releases soon with all the big, recent changes. I'll ping you here once that happens so you can update your stuff, and then once it's all lined up, we can start referencing it in the README.

**Comment by tobz** [comment]
@LukeMathWalker A belated response here, but, we've cut the new releases for `metrics` as of a few weeks ago. I'm not sure if your learning material is up-to-date with the latest changes yet, but we're probably good now to resume talking about getting that linked up in this repository.

**Comment by LukeMathWalker** [comment]
Thanks for the ping @tobz!
The workshop has been updated to the latest version of `metrics`.

**Comment by tobz** [comment]
Alright, I added a link to the workshop on the main README in 54939fa.

Let me know if that looks good/bad to you.

**Comment by LukeMathWalker** [comment]
I think linking to the repository would be better, since otherwise it's unclear how to actually progress through the workshop/what needs to be installed/etc.

**Comment by tobz** [comment]
Fair enough, yeah. Linked to the repository root. 👍🏻
