### ISSUE TITLE
Expose way to configure RollingSummary

### ISSUE THREAD

**Issue by rukai** [metrics-rs/metrics#430]
RollingSummary was internally introduced here https://github.com/metrics-rs/metrics/pull/306
But there is currently no way for the user to configure how long data is held onto for high level users of `metrics`/`metrics-exporter-prometheus`

**Comment by tobz** [comment]
Yeah, this is a reasonable request. I would accept a PR adding methods to the builder that allow configuring the bucket width and count.

**Comment by lilyball** [comment]
It looks like this was already done in https://github.com/metrics-rs/metrics/pull/444

**Comment by tobz** [comment]
Yep, just awaiting a release of `metrics-exporter-prometheus`, which should hopefully be doable somewhere between today and the next seven days. I've been queueing up a lot of changes to bundle together.

**Comment by tobz** [comment]
Released in `metrics-exporter-prometheus@v0.14.0`.
