### ISSUE TITLE
Where is the metrics-macros crate?

### ISSUE THREAD

**Issue by rukai** [metrics-rs/metrics#431]
The readme says it is hosted in this repo but I cant find it https://crates.io/crates/metrics-macros

**Comment by rukai** [comment]
Ah, figured it out https://github.com/metrics-rs/metrics/pull/386
Maybe the crate should have a deprecation message.

**Comment by tobz** [comment]
I pushed a final version -- `v0.7.1` -- that updated the README to mark the crate as no longer being used, and explains how to find the corresponding source code (in this repository) for a given version.
