### ISSUE TITLE
Switching to metrics-exporter-prometheus 0.13 breaks metrics

### ISSUE THREAD

**Issue by joske** [metrics-rs/metrics#440]
Hi,

we try to switch to the latest version (`metrics 0.22` and `metrics-exporter-prometheus 0.13`), but when bumping the latter, the exporter no longer exports any metrics. When switching back to 0.12 (no code changes), it just works. 

We use the following to instantiate the exporter:

```
    PrometheusBuilder::new().install().expect("can't build the prometheus exporter");
```

Any idea what could be wrong? I don't find anything useful in the Changelog or in the history.

**Comment by joske** [comment]
Please ignore, was caused by mixing different versions of the metrics crates.

**Comment by tobz** [comment]
No worries. This is a common issue when we push a new release of the main `metrics` crate, since everything that depends on `metrics` has to move in lockstep until we reach a 1.0 release. 😓 

Sorry about the confusion.
