### ISSUE TITLE
IntoF64 for more types?

### ISSUE THREAD

**Issue by bonsairobo** [metrics-rs/metrics#445]
I think it would be nice to impl `IntoF64` for more types that already `impl Into<f64>`, like `u32` and `i32`.

**Comment by tobz** [comment]
Yeah, that's a good point and good idea.

Can get to this at some point in the near future, but would also be a simple PR to whip up too, for anyone interested.

**Comment by tobz** [comment]
Added support for more types in 8f79f700beb0dbab8e4f8005ae3af95f483d6e73.

Released in `metrics@v0.22.3`.
