### ISSUE TITLE
small performance regression when no recorder set in 0.22

### ISSUE THREAD

**Issue by rukai** [metrics-rs/metrics#447]
I've noticed some of my benchmarks that exercise code that happens to use metrics had a 30% performance regression when I updated metrics from 0.21 to 0.22.
My solution to this was to set the benchmarks to always set a recorder, as previously they had no recorder set
This makes sense in our case since in our application we always have metrics enabled anyway, so this was just more realistic.
Once I did this I could observe no performance difference in the upgrade to 0.22

So personally this isnt causing me any issues.
But I thought it worth mentioning in case this is something you care about.

**Comment by tobz** [comment]
This is likely based on the structure of how we handle global vs local recorders.

There used to only be a single place we checked for the currently recorder, and that recorder was either the default no-op recorder or the installed global recorder. Now we check to see if a local recorder has been set, and if not, we then fallback and check if a global recorder has been set.

What is the actual wall clock time represented by that 30%, though?

**Comment by tobz** [comment]
Going to close this since there was never any more information and, based on the timing, likely related to the above, and thus inevitable and unavoidable

Thank you again for reporting it overall, though. :)
