### ISSUE TITLE
Remove upper-bound on ahash dependency version

### ISSUE THREAD

**Issue by AlexandreCassagne** [metrics-rs/metrics#454]
Commit f7e979a1b648e0dd8b25ff179c11ce5e15727fcc (`fix ahash MSRV nonsense`) locks down the version of ahash to <= 0.8.7

This breaks our build alongside actix-web v4.5.1 which calls for ahash 0.8.9.

I can see there are some more recent commits in ahash (main) but I do not understand the underlying issue well enough to determine if the bug was fixed there.

Can you link this issue to a blocking issue on ahash so we can un-pin the dependency again on this repo?

cc @tobz

**Comment by AlexandreCassagne** [comment]
Note: https://github.com/rust-lang/hashbrown/issues/504 - last comments suggest the the MSRV bump was fixed in a patch tbc

**Comment by AlexandreCassagne** [comment]
It looks like this MSRV bump was rolled back in this PR
https://github.com/tkaitchuck/aHash/pull/208

**Comment by tobz** [comment]
Oh neat. If the MSRV bump has been reverted as of `ahash` 0.8.8, then we can remove the range constraint and instead pin to 0.8.8.

**Comment by tobz** [comment]
Released in `metrics@v0.22.2`.

**Comment by AlexandreCassagne** [comment]
Thanks @tobz.
