### ISSUE TITLE
Make with_recorder public

### ISSUE THREAD

**Issue by jaskij** [metrics-rs/metrics#473]
Can `with_recorder()` be made public?

As discussed on Discord, macros can be hard to use in some cases, and some developers strongly prefer plain functions. It would be desirable to have a public API that allows creating and describing metrics without them. As is, it seems that making `with_recorder()` public is the shortest route to achieve this.

The use case where this came up are wrappers, which wrap an action together with it's metric. While it is possible to do that right now, the types and traits involved are hard to find.

**Comment by tobz** [comment]
I don't see a strong reason why it couldn't be made public.

So long as the documentation indicates that it is not the preferred way to interact with the global recorder -- the macros are -- then it should be fine.

**Comment by jaskij** [comment]
I could make a quick PR soon-ish, or do you want to wait for someone else to weigh in?

**Comment by tobz** [comment]
I am the alpha and the omega in these parts 😂 so feel free to just open a PR.
