### ISSUE TITLE
Make it possible to extract `&'static T` from `Cow<'static, T>`.

### ISSUE THREAD

**Issue by Dav1dde** [metrics-rs/metrics#474]
I am implementing a recorder from `metrics` to `sentry::metrics` and Sentry currently uses `std::cow::Cow<'static, str>` for tags and metric names. If it was possible to extract a `&'static str` from a `SharedStr` many `to_owned` calls would be saved.

I tried implementing it myself but it seems easy to get wrong.

**Comment by tobz** [comment]
The lifetime used does not change the fact the wrapper might be holding an owned value, which means you _cannot_ provide a static reference to it, so it has to be something like `as_borrowed(&self) -> Option<&'a T>`, or an impl to convert to `std::borrow::Cow`, which is also possible.
