### ISSUE TITLE
Support set metrics

### ISSUE THREAD

**Issue by Dav1dde** [metrics-rs/metrics#479]
There is currently no way to emit set metrics via metrics-rs.

For example, [statsd](https://statsd.readthedocs.io/en/v3.3/types.html#sets) and [Sentry](https://docs.sentry.io/product/metrics/#metric-types) support sets natively.

**Comment by tobz** [comment]
This is something I'm not looking to support with `metrics`, as it can be more easily handled by applications themselves, and tracked directly as a gauge.

**Comment by Dav1dde** [comment]
How would the application track a set as a gauge? This does not work for anything distributed.

**Comment by tobz** [comment]
You're right: it would only be aggregated at the application-level, so perhaps by pod or by host. This is also how most metrics platforms that "support" StatsD (and thus sets) do it, though: They don't natively send the set data to the backend and do global aggregation, they just roll up the values locally and emit a gauge.

**Comment by Dav1dde** [comment]
That's unfortunate for all platforms that do support proper sets. But fair enough.
