### ISSUE TITLE
Make `Snapshotter` `Clone`

### ISSUE THREAD

**Issue by blp** [metrics-rs/metrics#486]
`Snapshotter` is just a wrapper around an `Arc` and I don't know why it can't be `Clone`d. I suspect it's just an oversight. It would be convenient to make it easy to pass it around multiple places.

**Comment by tobz** [comment]
I think the original thought was that it's not really meant to be used for anything except tests, where cloning it would be... I don't know why you would ever have to clone it in a test, basically.

There's no _technical_ reason it can't be `Clone`, but what's the usecase here?

**Comment by blp** [comment]
I have multiple tests, so I used a `OnceLock` to make a globally accessible `Snapshotter` so that I could use it from all of them, and then I discovered that I couldn't clone it.

For now, I just wrapped `Snapshotter` in another `Arc`, which also works OK.

**Comment by tobz** [comment]
A better approach (IMO) would be to use [`with_local_recorder`](https://docs.rs/metrics/latest/metrics/fn.with_local_recorder.html), which is designed specifically for tests in order to avoid having to do tricks with a global recorder.

**Comment by blp** [comment]
I assumed that `with_local_recorder` wouldn't work with additional threads spawned by the test (but I haven't tried it).

**Comment by tobz** [comment]
Ah, yeah, it wouldn't work for anything other than the thread that `with_local_recorder` is called on.

In that case, would be happy to review a PR adding `Clone` to `Snapshotter`.

**Comment by tobz** [comment]
Oh, woops! Just realized this will be implemented once #472 is released.

**Comment by blp** [comment]
> Oh, woops! Just realized this will be implemented once #472 is released.

Oh, perfect, thank you!

**Comment by tobz** [comment]
Late response, but: this was released in `metrics-util@v0.17.0`.
