### ISSUE TITLE
Key construction from labels always allocate

### ISSUE THREAD

**Issue by jean-airoldie** [metrics-rs/metrics#49]
Currently creating a key from labels will allocate a vector every time, even if the labels are `&'static str`.
https://github.com/metrics-rs/metrics/blob/2f3e344705867f464c60cc2d7fb81ce741b2f715/metrics-core/src/lib.rs#L98
https://github.com/metrics-rs/metrics/blob/2f3e344705867f464c60cc2d7fb81ce741b2f715/metrics-core/src/lib.rs#L211
This means that the metrics macros might potentially allocate at every call. Obviously this is not ideal.

A solution from metrics side would be for a `Key` to be constructible with a label without any allocation. So in the same sense that `name` is a `ScopedString`, the labels could something like:
`Cow<&'static, [&'static str]>`. So for the special case where the labels are a slice of `&'static str` this would not allocate. I think this would be ideal.

**Comment by tobz** [comment]
This will be solved by #80 which caches callsite identifiers when labels are entirely static.

**Comment by tobz** [comment]
We've reworked how keys are handled in #87, but this is still covered, ultimately, by the caching mechanism introduced in #80, so I'm going to close this.
