### ISSUE TITLE
Discord channel invite is invalid

### ISSUE THREAD

**Issue by jfernandez** [metrics-rs/metrics#493]
Hey folks, is the Discord server still active? All the invite links I've found for the project no longer work.

**Comment by tobz** [comment]
Woops, looks like the link expired.

I've updated it with a new, valid invite link. Thanks for reporting!

**Comment by jfernandez** [comment]
@tobz the /tokio link is also invalid

**Comment by tobz** [comment]
Weird... seems to work for me, although I'm already in the server.

Are you getting an error or what?

**Comment by jfernandez** [comment]
This is what I'm getting:

![image](https://github.com/metrics-rs/metrics/assets/3172/d7046a81-dfb0-4876-9edc-4bfdc8b64877)

**Comment by tobz** [comment]
Yeah, weird... even in incognito mode, it still ended up taking me into Discord. Must have just been because I was already in the server.

Anyways, I tried to generate another link (the last one I nabbed while on mobile) so hopefully second try's a charm.

**Comment by jfernandez** [comment]
It's working now. ty
