### ISSUE TITLE
Gigibyte → Gibibyte

### ISSUE THREAD

**Issue by hrxi** [metrics-rs/metrics#497]
https://github.com/metrics-rs/metrics/blob/f84efc4e0f637c5c1dbbeccb219fe061b3b6cb6b/metrics/src/common.rs#L92

https://en.wikipedia.org/w/index.php?title=Byte&oldid=1227965783#Multiple-byte_units

Seems like a typo, but probably difficult to rectify due to backward compatibility guarantees.

**Comment by tobz** [comment]
Definitely a typo, and we can definitely rectify that.... the power of not being at v1 yet! 😂

**Comment by etolbakov** [comment]
@tobz 
As a part of "getting familiar with the code base" activity I decided to make come up with the improvement.
Could you please take a look when you have time if this is something that you expected
