### ISSUE TITLE
Investigate attaching tags to metrics.

### ISSUE THREAD

**Issue by tobz** [metrics-rs/metrics#5]
Naive thought is that we switch to a composite metric key internally -- an enum, really -- where we have untagged and tagged metrics.

Would be trivial to hash so that normal aggregation worked, and shouldn't add a ton of overhead storage-wise.  Biggest issue would likely be the performance of sending the tags with the metric, just in terms of memory being moved around.

We might be able to do some `Scope`-esque magic with keeping a registry or something, but who knows.

**Comment by samanpa** [comment]
+1 I would like to use metrics-rs with an "exporter" that has tags as well as keys.

**Comment by tobz** [comment]
I'm working on this in #23 👍
