### ISSUE TITLE
Key construction from `&str` always allocate

### ISSUE THREAD

**Issue by jean-airoldie** [metrics-rs/metrics#50]
Currently creating a `Key` from that `&str` always allocates (unless the `&'static str`), which is not ideal.

Instead we could represent a `Key` as the hash of a perfect hash function for a combination of name + label. Since the hash would be a `Copy` type, we don't need to worry about ownership. So conceptually the `Key` would be a handle to an allocated name + labels combination. To achieve this we could use a [string interning](https://en.wikipedia.org/wiki/String_interning) mechanism.

So i think that the metrics recording should be done this way:
* Create a `Key` from the hash of a name + labels. This never allocates.
* Attempt to record a metric using the `Key`:
  * If this fails (returns an error):
    * Register the `Key` using the name + labels (this allocates)
    * Record the metric (this will never fail).

This way, each name + labels combination will allocate at most once.

edit: I found a better solution

**Comment by tobz** [comment]
We've more or less improved key building/allocation in #87, so going to close this.
