### ISSUE TITLE
Routing more than one pattern to the same `Recorder`

### ISSUE THREAD

**Issue by david-perez** [metrics-rs/metrics#506]
[`metrics_util::layers::RouterBuilder::add_route`](https://docs.rs/metrics-util/latest/metrics_util/layers/struct.RouterBuilder.html#method.add_route) takes ownership of the recorder, which means it can only handle one pattern/mask combination.

Could we make it take in an `Iterator` of patterns, or an `Arc<R: Recorder>`?

**Comment by tobz** [comment]
I _think_ all we would potentially need to do is add a blanket impl in `metrics` for `impl<R> Recorder for Arc<R> where R: Recorder`? That would satisfy needing to provide an owned recorder without messing with the current `add_route` signature.
