### ISSUE TITLE
Add  `record_many` to histogram

### ISSUE THREAD

**Issue by 0xdeafbeef** [metrics-rs/metrics#509]
I want to reexport tokio metrics, they already provide bucketed data.
To reexport it, you should write such code:

```rs
 let hist = metrics::histogram!("tokio_poll_count_time");
  for (idx, value) in histogram.iter().enumerate() {
      let bucket_value = LOG_BUCKETS[idx];
      for _ in 0..*value {
          hist.record(bucket_value);
      }
   }
```                

Is it possible to add 
```rs
fn record_many(&self, value: f64, count: u64);
````
 to `HistogramFn` to not burn cpu cycles? Or maybe there is a better way?

**Comment by 0xdeafbeef** [comment]
maybe even
```rs
pub trait HistogramFn {
    /// Records a value into the histogram.
    fn record(&self, value: f64);

    fn record_many(&self, value: f64, count: u64) {
        for _ in 0..count {
            self.record(value);
        }
    }
}

```

I can open a pr if you agree with such interface

**Comment by tobz** [comment]
Overall, I'm fine with the idea of adding `HistogramFn::record_many` with the proposed method signature. I would definitely want the second version so that we can add it as a non-breaking change, and I would gladly accept a PR for that implementation. 👍🏻
