### ISSUE TITLE
`home` dependency pin causes compatibility issues with other crates

### ISSUE THREAD

**Issue by cgbur** [metrics-rs/metrics#526]
Currently the [home](https://crates.io/crates/home) crate is pinned to [=0.5.5](https://github.com/metrics-rs/metrics/blob/c06d68e1c72b711559cbb19d028d2dce773e7d65/metrics-exporter-tcp/Cargo.toml#L30) across the metrics crates, this causes issues currently for any project which has a transitive dependency on the very popular [which](https://crates.io/crates/which) crate, which currently targets the latest `0.5.9` release of `home` that came out ~1 year ago.

**Comment by tobz** [comment]
We likely could bump this to 0.5.9 now, yeah. given that our MSRV is 1.70.0.
