### ISSUE TITLE
`metrics` is published to crates.io without a README

### ISSUE THREAD

**Issue by abonander** [metrics-rs/metrics#539]
One of my coworkers opened a PR to one of our projects adding this crate and `metrics-exporter-prometheus`, and not being familiar with either crate, I decided to investigate.

One of the first things I look at when examining a new crate is the crates.io page to check the version history and get a first look through the README. The quality of the documentation available gives me an idea of the code quality of a crate and the competency of its author(s). First impressions are everything, you know.

I was a little dismayed to see that `metrics` is published without a README:

![image](https://github.com/user-attachments/assets/56b41e47-f988-4639-b903-3eedc1c72fc4)

which often suggests to me either a namesquatted crate, or a crate that's purely implementation details (like a proc-macro crate), or something that's in very early development. It doesn't exactly inspire confidence.

Clicking through to the repository tells a much different story, however. And the release history suggests a highly mature and well maintained crate. I think the crates.io page should reflect that.

It's an easy fix so I'd happily open a PR, but there's the question of _which_ README to publish:

* [README.md](https://github.com/metrics-rs/metrics/blob/main/README.md), with more information about the project as a whole, or:
* [metrics/README.md](https://github.com/metrics-rs/metrics/blob/main/metrics/README.md), which doesn't have as much information, but is specifically for `metrics`?

**Comment by tobz** [comment]
What URL are you browsing when you see that screen?

As far as I can tell, the main `metrics` crate shows the README just fine when browsing https://crates.io/crates/metrics:

![Screenshot_20241101-151740.png](https://github.com/user-attachments/assets/d3010b4c-e2ba-4308-9311-14822bed02fc)

**Comment by abonander** [comment]
Oh! I think it's a bad interaction between crates.io and my ad blocker.

I looked at the network requests when loading the page, and lo and behold it's blocking the request for the README: 
![image](https://github.com/user-attachments/assets/19e0a983-3a00-4590-8b55-3904038c3b1e)

Disabling uBlock Origin shows the README.

Looks like it's hitting a filter rule that blocks certain analytics, which just so happens to match the name of the crate!

![image](https://github.com/user-attachments/assets/3b23cac9-d252-4eb7-bd3e-1028777c56f8)

It's not a problem with this crate or crates.io, it's an issue with this filter list.
