### ISSUE TITLE
Grafana integration?

### ISSUE THREAD

**Issue by expenses** [metrics-rs/metrics#54]
Hi, I'd really like to be able to use [grafana](https://grafana.com/) to visualise metrics. Currently, the best way to do this is to prometheus and connect that to grafana, but I'd much rather run a server that confirms to the [grafana json datasource](https://github.com/simPod/grafana-json-datasource) api.

Does your current http exporter use an standard api? Perhaps you could use that one.

**Comment by tobz** [comment]
@expenses Hey there!

Currently, `metrics` focuses on acting as a conduit to get metrics out of your applications and into existing metrics storage systems.  None of the existing exporters currently store any metrics, which would be a requirement, as far as I can see, for Grafana to use them as a datasource.

Once an exporter starts going beyond "grab the current set of metrics and return them" into a place of storing them longer-term, providing querying, etc, then we've moved past exporting, and that's something that most people rely on existing systems, like you mentioned, such as Prometheus or InfluxDB, to handle for them.

With all of that said: I'd be happy to accept a PR, or help develop a basic exporter/storage layer that provides a toy version of a storage backend, serving up a Grafana-compatible JSON datasource.  I can certainly see the value in "add metrics, then point Grafana at your app" for getting started, or for use cases where it'd be nice just to have some simple long-term metrics storage built-in without another service required.

How does that sound?

**Comment by expenses** [comment]
Yeah, I think it would be useful to have that. Unfortunately, writing an embedded timeseries DB (which is the ideal) is pretty complex, and involves a lot of considerations. I think for the moment it would be best to stick to something like InfluxDB or Graphite.

It's a shame that Grafana doesn't have its own database; that would definitely make the choices easier.

**Comment by tobz** [comment]
Yup, absolutely. :)

Definitely let us know if you have any other thoughts/concerns about metrics!
