### ISSUE TITLE
I think one of the great features of [`metrics_util::layers::Layer`](https://docs.rs/metrics-util/latest/metrics_util/layers/trait.Layer.html) is how it makes `Recorder`s composable. Usually `Recorder`s hold a _registry_ of all metrics emitted. It'd be cool if we could build and compose registry-agnostic `Recorder`s, so that the same `Recorder` implementation could work with e.g. a registry backed by a hash map [or by a struct](https://github.com/metrics-rs/metrics/discussions/468).

### ISSUE THREAD

**Issue by Sopheap-cloud** [metrics-rs/metrics#545]
I think one of the great features of [`metrics_util::layers::Layer`](https://docs.rs/metrics-util/latest/metrics_util/layers/trait.Layer.html) is how it makes `Recorder`s composable. Usually `Recorder`s hold a _registry_ of all metrics emitted. It'd be cool if we could build and compose registry-agnostic `Recorder`s, so that the same `Recorder` implementation could work with e.g. a registry backed by a hash map [or by a struct](https://github.com/metrics-rs/metrics/discussions/468).

The [`metrics_util::registry::Registry`](https://docs.rs/metrics-util/latest/metrics_util/registry/struct.Registry.html) struct is a building block that already offers a nice interface I'd expect an arbitrary registry to have: at the very least it needs to have methods to get and register metrics (used by the `Recorder`), and methods to visit and drain metrics (used by the "exporter", the piece of code responsible for transferring the metrics out of the `Recorder` and into the sink).

Does this sound reasonable? Should we have a `Registry` trait, perhaps in the `metrics_util` crate?

_Originally posted by @david-perez in https://github.com/metrics-rs/metrics/discussions/481_

**Comment by tobz** [comment]
Closing due to spam.

**Comment by Sopheap-cloud** [comment]
[Uploading _chat 2.txt…]()
