### ISSUE TITLE
Arc-Swap dependency update

### ISSUE THREAD

**Issue by j-t-d** [metrics-rs/metrics#57]
Hi,

I've been using the really amazing cargo-deny (https://github.com/EmbarkStudios/cargo-deny) crate for removing duplicate crates to help speed up build times. metrics-runtime (0.12.0) is using an older version of arc-swap (0.3.11). I was wondering if we could bump that up to 0.4 to match signal-hook-registry and slog-scope.

**Comment by tobz** [comment]
Looks like 0.4 was a breaking release for `arc_swap`, and I don't really have any tests to gain confidence refactoring the code that uses it, so this might be a while.

**Comment by j-t-d** [comment]
Ah yes, I ran into a similar issue when updating some of our stuff here. Lease is basically load() now. It gives you back a guard that drops the lease when it leaves scope. Use as_ref() to get an immutable reference from the guard.
