### ISSUE TITLE
Crossbeam-Epoch dependency

### ISSUE THREAD

**Issue by j-t-d** [metrics-rs/metrics#58]
Similar to #57, cargo-deny is showing a dependency on an older version of crossbeam-epoch, which has a dependency on arrayvec 0.4.12. 

slog brings in a series of dependencies that uses the latest version of arrayvec (0.5.1). Updating to 0.8 of epoch actually removes the arrayvec dependency.

**Comment by tobz** [comment]
Heyo!

Saw your other ticket as well: happy to bump up version dependencies, but would you be willing to make a PR to do both of those things?

**Comment by j-t-d** [comment]
Unfortunately it's easier for me to make an issue than a PR from work :(

**Comment by tobz** [comment]
Released `metrics-util@0.3.1` which switched to `crossbeam-epoch@^0.8`.
