### ISSUE TITLE
Floating point gauge/histograms?

### ISSUE THREAD

**Issue by expenses** [metrics-rs/metrics#60]
Hi, maybe I'm missing something, but is there a reason that `metrics` doesn't support `f64` values? Percentages are great most of the time, but sometimes you need something less bounded, CPU usage, for example, goes to 400% etc if you have multiple cores.

**Comment by RAnders00** [comment]
Same thing for counters. Prometheus supports them as well, and semantically they also make sense, for example when counting time, e.g. `process_cpu_seconds_total` or similar.

**Comment by tobz** [comment]
This is something we're considering doing in an ongoing refactor: #71. 

My biggest problem with going full `f64` is two-fold: loss of compile-time enforcement of counter monotonicity, and support for `f64` in histogram crates comes with meaningful trade-offs.

The counter monotonicity one speaks for itself, but the more interesting one is the histograms.

There are two main histogram crates in the Rust ecosystem: `hdrhistogram` and `sketches_ddsketch`.  `hdrhistogram` is the most commonly-used one, as it's well worn, has sensible defaults, but requires unsigned integer values for measurement.  `sketches_ddsketch` is a newcomer, but based on Datadog's `DDSketch`, and supports `f64` values, but requires configuration beyond the defaults to properly support capturing nanosecond resolution in measurements.

Our tests with `sketches_ddsketch` led us down a path where we would be forced to configure them such that they consumed a ton of memory per histogram -- we're talking 200-300kb per unique histogram -- and we'd still end up with unsatisfactory accuracy for quantiles at the extreme.

Practically speaking, while I understand that Prometheus has pushed a schema/ethos that supports people utilizing floating-point integers, especially doing things like seconds with fractional nanoseconds, my personal experience is that doing that in Rust is just about as hard as using nanoseconds in the first place and adjusting your unit base.

All of that said, we're still considering it if we can make it work such that it fits our requirements, but early tests so far haven't proven very fruitful.

**Comment by RAnders00** [comment]
Thank you for the in-depth comment. I actually hadn't thought about using nanoseconds/milliseconds instead of seconds and wanting to use floating points numbers. I think that's a sensible solution.

**Comment by tobz** [comment]
👍 

I appreciate these issues being submitted either way, because ultimately, everyone has their own lived experiences when it comes to what works well for them, etc.  It might be easy to switch from seconds to nanoseconds, but if your whole codebase is already using `f64`/seconds, then I could empathize with not wanting to switch.

The more information like this that we get, the better we can prioritize for what we look into doing, and what solutions might best serve everyone.  I'll leave this issue open since we haven't yet made a final decision on whether or not we can support `f64` measurements.

**Comment by tobz** [comment]
I'm going to close this issue as a "we won't do this".

Having worked through the issues I mentioned in my earlier comment, at this time, switching to floating-point values would be an outsized amount of work, both from a performance aspect as well as a "does this provide accurate data?" aspect.

**Comment by loyd** [comment]
So, it's impossible to produce something like `node_cpu_seconds_total` without a workaround (like forcing a right type in recorder implementation), innit?

**Comment by tobz** [comment]
Counters are still `u64` and will be that way for the foreseeable future, yes.  Histograms ended up being changed to `f64`, and gauges have been `f64` for a while, as well.
